// import DashboardLayout from "@/components/dashboard/DashboardLayout";
// import { AuthProvider } from "@/utils/Guard";

// export const metadata = {
//   title: "Contact us",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <AuthProvider>
//       <DashboardLayout>
//         {children}
//       </DashboardLayout>
//     </AuthProvider>
//   );
// }


// app/page.js
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { AuthProvider } from "@/utils/Guard";
import { ProfileProvider } from "@/utils/ProfileContext";

export const metadata = {
  title: "Avöyes ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <ProfileProvider>
        <DashboardLayout>
          {children}
        </DashboardLayout>
      </ProfileProvider>
    </AuthProvider>
  );
}


